image: python:3.5.1

pipelines:
  branches:
    master:
      - step:
          script:
            # - apt-get update
            # - apt-get install -y zip # required if you want to zip repository objects
            - pip install boto3==1.3.0 # required for s3_upload.py
            # the first argument is the name of the existing S3 bucket to upload the artefact to
            # the second argument is the artefact to be uploaded
            # the third argument is the the bucket key
            - pip install gitpython
            - apt-get update && apt-get install -y zip
            - python gitpy.py
            #- git checkout -b stage
            #- git add .
            #- git config --global user.email "ratulbasak93@gmail.com"
            #- git config --global user.name "ratulbasak93"
            #- git commit -m "updated repo"
            #- git config --local -l
            #- git push origin stage
            #- zip -r dotnet-api.zip ./*
            #- python s3_upload.py codebase-build dotnet-api.zip dotnet-api.zip #  run the deployment script
            # Example command line parameters. Replace with your values
            #- python s3_upload.py bb-s3-upload SampleApp_Linux.zip SampleApp_Linux # run the deployment script
