version: '3'

services:
    nginx:
        image: nginx
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        links:
            - dotnetapi

    dotnetapi:
        image: apidocker
        build:
           context: .
           dockerfile: ./Dockerfile
        container_name: dotnetapi
        ports:
            - "5000:5000"

